### ISSUE TITLE
BACKEND

### ISSUE THREAD

**Issue by jmr230584** [CLOUDYURI9/backend-biblioteautomatizada#2]
- Na classe Aluno.ts retirar do construtor o "ra" do aluno, o "ra" é gerado no banco, se estiver no construtor ele passa a ser inserção manual, declare o atributo dessa forma `private ra: string = "";`
- Posso ter esqueci de ter olhado algo, verifica se os demais itens gerado no banco se está fora do construtor.

**Comment by CLOUDYURI9** [comment]
Retirado do construtor do Aluno.ts o atriburo RA do aluno.
